# Generated by Django 5.1.15 on 2026-01-19 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20160402_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='portrait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.document'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filetype',
            field=models.CharField(choices=[('IMG', 'Image'), ('AUD', 'Audio'), ('MOV', 'Movie')], default='IMG', max_length=3),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='publicity',
            field=models.CharField(choices=[('PRI', 'Private'), ('FRO', 'Friends-Only'), ('PUB', 'Public')], default='PRI', max_length=3),
        ),
        migrations.AlterField(
            model_name='gallerycollab',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gallerycollab',
            name='publicity',
            field=models.CharField(choices=[('PRI', 'Private'), ('FRO', 'Friends-Only'), ('PUB', 'Public')], default='PRI', max_length=3),
        ),
        migrations.AlterField(
            model_name='human',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicitysetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='work',
            name='publicity',
            field=models.CharField(choices=[('PRI', 'Private'), ('FRO', 'Friends-Only'), ('PUB', 'Public')], default='PRI', max_length=3),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
