# Generated by Django 5.1.15 on 2026-01-25 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_human_portrait_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.document'),
        ),
    ]
