# Generated by Django 5.1.15 on 2026-01-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_work_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='pictureUrl',
        ),
        migrations.RemoveField(
            model_name='work',
            name='thumbnailUrl',
        ),
    ]
