# Generated by Django 5.1.15 on 2026-02-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_document_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_string', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('invalidate_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='secret_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.secretkey'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('contact_method', models.CharField(choices=[('EML', 'E-mail'), ('SMS', 'Text Message')], default='EML', max_length=3)),
                ('interests', models.ManyToManyField(related_name='subscribers', to='gallery.tag')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.human')),
            ],
        ),
    ]
