# Generated by Django 5.1.15 on 2026-03-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_secretkey_gallery_secret_key_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='contact_method',
            field=models.CharField(choices=[('EML', 'E-mail'), ('SMS', 'Text Message'), ('DIS', 'Discord Channel')], default='EML', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together={('author', 'urlname')},
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('gallery', 'urlname')},
        ),
    ]
