# Generated by Django 5.1.15 on 2026-03-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_alter_subscriber_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='SubscriberBeenNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.subscriber')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.work')),
            ],
            options={
                'unique_together': {('subscriber', 'work')},
            },
        ),
    ]
