# Generated by Django 5.1.15 on 2026-03-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_subscriber_url_alter_subscriber_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
