# Generated by Django 5.1.15 on 2026-03-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_subscriber_email_alter_subscriber_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='happened_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='happenedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
