# Generated by Django 5.1.15 on 2026-07-10 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_document_happened_at_work_happeneddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='secret_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.secretkey'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filetype',
            field=models.CharField(choices=[('IMG', 'Image'), ('THU', 'Thumbnail'), ('AUD', 'Audio'), ('MOV', 'Movie')], default='IMG', max_length=3),
        ),
        migrations.CreateModel(
            name='GalleryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.human')),
            ],
        ),
    ]
