# Generated by Django 5.1.15 on 2026-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_remove_gallery_secret_key_subscriber_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='sort_order',
            field=models.CharField(choices=[('SEQ', 'Order Added'), ('TTL', 'Alphabetical by Title'), ('CRO', 'Chronological'), ('REV', 'Reverse Chronological')], default='SEQ', max_length=3),
        ),
    ]
