# Generated by Django 5.1.15 on 2026-09-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0021_gallery_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.document'),
        ),
    ]
